const jobs = [
    {
        title: "Choose Flooring",
        id: 1,
        dependencies: [],
        category: "Kitchen",
    },
    {
        title: "Choose Kitchen",
        id: 2,
        dependencies: [],
        category: "Kitchen",
    },
    {
        title: "Level floor",
        id: 3,
        dependencies: [],
        category: "Kitchen",
    },
    {
        title: "Fit kitchen units",
        id: 4,
        dependencies: [1, 2, 3, 6, 7],
        category: "Kitchen",
    },
    {
        title: "Fit worktops",
        id: 5,
        dependencies: [4],
        category: "Kitchen",
    },
    {
        title: "Paint kitchen ceiling",
        id: 6,
        dependencies: [],
        category: "Kitchen",
    },
    {
        title: "Paint kitchen walls",
        id: 7,
        dependencies: [8],
        category: "Kitchen",
    },
    {
        title: "Choose paint colour",
        id: 8,
        dependencies: [],
        category: "Kitchen",
    },
    {
        title: "Choose worktops",
        id: 9,
        dependencies: [],
        category: "Kitchen",
    },
    {
        title: "Fit appliances",
        id: 10,
        dependencies: [4],
        category: "Kitchen",
    },
    {
        title: "2nd fix electrics",
        id: 11,
        dependencies: [4],
        category: "Kitchen",
    },
    {
        title: "2nd fix plumbing",
        id: 12,
        dependencies: [2],
        category: "Kitchen",
    },
    {
        title: "Fit skirting",
        id: 13,
        dependencies: [4],
        category: "Kitchen",
    },
    {
        title: "Fit flooring",
        id: 34,
        dependencies: [1, 3],
        category: "Kitchen",
    },
    {
        title: "Remove skirting",
        id: 14,
        dependencies: [],
        category: "Dining Room",
    },
    {
        title: "Take out internal wall",
        id: 15,
        dependencies: [],
        category: "Dining Room",
    },
    {
        title: "Cut bi-fold hole",
        id: 16,
        dependencies: [],
        category: "Dining Room",
    },
    {
        title: "1 fix electrics",
        id: 17,
        dependencies: [17],
        category: "Dining Room",
    },
    {
        title: "Decide sockets & lights",
        id: 18,
        dependencies: [],
        category: "Dining Room",
    },
    {
        title: "Fit flooring",
        id: 19,
        dependencies: [14, 15, 16, 20, 21, 34],
        category: "Dining Room",
    },
    {
        title: "Plaster",
        id: 20,
        dependencies: [17, 21, 22],
        category: "Dining Room",
    },
    {
        title: "Decide on internal doors",
        id: 21,
        dependencies: [],
        category: "Dining Room",
    },
    {
        title: "Fit door framing",
        id: 22,
        dependencies: [21],
        category: "Dining Room",
    },
    {
        title: "Fit internal doors",
        id: 23,
        dependencies: [21],
        category: "Dining Room",
    },
    {
        title: "Fit bi-folds",
        id: 24,
        dependencies: [16],
        category: "Dining Room",
    },
    {
        title: "2 fix electrics",
        id: 25,
        dependencies: [20],
        category: "Dining Room",
    },
    {
        title: "Fit internal window",
        id: 26,
        dependencies: [20],
        category: "Dining Room",
    },
    {
        title: "Choose paint colour",
        id: 27,
        dependencies: [],
        category: "Dining Room",
    },
    {
        title: "Paint ceiling",
        id: 28,
        dependencies: [20],
        category: "Dining Room",
    },
    {
        title: "Paint walls",
        id: 29,
        dependencies: [20, 27],
        category: "Dining Room",
    },
    {
        title: "Fit skirting (if any)",
        id: 30,
        dependencies: [19, 20],
        category: "Dining Room",
    },
    {
        title: "Paint woodwork",
        id: 31,
        dependencies: [30],
        category: "Dining Room",
    },
    { title: "Choose door", id: 32, dependencies: [], category: "Dining Room" },
    {
        title: "Fit door",
        id: 33,
        dependencies: [32, 15],
        category: "Dining Room",
    },
];
