const jobs = [
    {
        title: "Choose Flooring",
        id: 1,
        dependencies: [],
        category: "Kitchen",
    },
    {
        title: "Choose Kitchen",
        id: 2,
        dependencies: [],
        category: "Kitchen",
    },
    {
        title: "Level floor",
        id: 3,
        dependencies: [],
        category: "Kitchen",
    },
    {
        title: "Fit kitchen units",
        id: 4,
        dependencies: [1,2,3,6,7],
        category: "Kitchen",
    },
    {
        title: "Fit worktops",
        id: 5,
        dependencies: [4],
        category: "Kitchen",
    },
    {
        title: "Paint kitchen ceiling",
        id: 6,
        dependencies: [],
        category: "Kitchen",
    },
    {
        title: "Paint kitchen walls",
        id: 7,
        dependencies: [8],
        category: "Kitchen",
    },
    {
        title: "Choose paint colour",
        id: 8,
        dependencies: [],
        category: "Kitchen",
    },
    {
        title: "Choose worktops",
        id: 10,
        dependencies: [],
        category: "Kitchen",
    },
    {
        title: "Fit appliances",
        id: 11,
        dependencies: [4],
        category: "Kitchen",
    },
    {
        title: "2nd fix electrics",
        id: 12,
        dependencies: [4],
        category: "Kitchen",
    },
    {
        title: "2nd fix plumbing",
        id: 13,
        dependencies: [2],
        category: "Kitchen",
    },
    {
        title: "Fit skirting",
        id: 14,
        dependencies: [4],
        category: "Kitchen",
    },
];
